////////////////////////////////////////////////////////////////////////////////
//
// Filename:	./toplevel.v
//
// Project:	OpenZ7, an open source Zynq demo based on the Arty Z7-20
//
// DO NOT EDIT THIS FILE!
// Computer Generated: This file is computer generated by AUTOFPGA. DO NOT EDIT.
// DO NOT EDIT THIS FILE!
//
// CmdLine:	autofpga autofpga -d -o . global.txt axilboard.txt controlbus.txt zynqps.txt
//
// Creator:	Dan Gisselquist, Ph.D.
//		Gisselquist Technology, LLC
//
////////////////////////////////////////////////////////////////////////////////
//
// Copyright (C) 2020, Gisselquist Technology, LLC
//
// This program is free software (firmware): you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation, either version 3 of the License, or (at
// your option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTIBILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  (It's in the $(ROOT)/doc directory.  Run make with no
// target there if the PDF file isn't present.)  If not, see
// <http://www.gnu.org/licenses/> for a copy.
//
// License:	GPL, v3, as defined and found on www.gnu.org,
//		http://www.gnu.org/licenses/gpl.html
//
//
////////////////////////////////////////////////////////////////////////////////
//
//
`default_nettype	none


//
// Here we declare our toplevel.v (toplevel) design module.
// All design logic must take place beneath this top level.
//
// The port declarations just copy data from the @TOP.PORTLIST
// key, or equivalently from the @MAIN.PORTLIST key if
// @TOP.PORTLIST is absent.  For those peripherals that don't need
// any top level logic, the @MAIN.PORTLIST should be sufficent,
// so the @TOP.PORTLIST key may be left undefined.
//
// The only exception is that any clocks with CLOCK.TOP tags will
// also appear in this list
//
module	toplevel(
	// Core Zynq PS signals
	DDR_Clk_n,
	DDR_Clk,
	DDR_CS_n, DDR_CKE, DDR_RAS_n, DDR_WEB, DDR_CAS_n,
	DDR_DRSTB, DDR_ODT,
	DDR_BankAddr, DDR_Addr,
	DDR_VRN, DDR_VRP,
	DDR_DM, DDR_DQ, DDR_DQS_n, DDR_DQS,
	//
	PS_SRSTB, PS_CLK, PS_PORB,
		i_sw, i_btn, o_led,
		o_redled, o_grnled, o_bluled);
	//
	// Declaring our input and output ports.  We listed these above,
	// now we are declaring them here.
	//
	// These declarations just copy data from the @TOP.IODECLS key,
	// or from the @MAIN.IODECL key if @TOP.IODECL is absent.  For
	// those peripherals that don't do anything at the top level,
	// the @MAIN.IODECL key should be sufficient, so the @TOP.IODECL
	// key may be left undefined.
	//
	// We start with any @CLOCK.TOP keys
	//
	inout	wire		DDR_CAS_n;
	inout	wire		DDR_CKE;
	inout	wire		DDR_Clk_n;
	inout	wire		DDR_Clk;
	inout	wire		DDR_CS_n;
	inout	wire		DDR_DRSTB;
	inout	wire		DDR_ODT;
	inout	wire		DDR_RAS_n;
	inout	wire		DDR_WEB;
	inout	wire	[2:0]	DDR_BankAddr;
	inout	wire	[14:0]	DDR_Addr;
	inout	wire		DDR_VRN;
	inout	wire		DDR_VRP;
	inout	wire	[3:0]	DDR_DM;
	inout	wire	[31:0]	DDR_DQ;
	inout	wire	[3:0]	DDR_DQS_n;
	inout	wire	[3:0]	DDR_DQS;
	inout	wire		PS_SRSTB;
	inout	wire		PS_CLK;
	inout	wire		PS_PORB;
	input	wire	[1:0]	i_sw;
	input	wire	[3:0]	i_btn;
	output	wire	[3:0]	o_led;
	output	wire	[1:0]	o_redled;
	output	wire	[1:0]	o_grnled;
	output	wire	[1:0]	o_bluled;


	//
	// Declaring component data, internal wires and registers
	//
	// These declarations just copy data from the @TOP.DEFNS key
	// within the component data files.
	//
	//
	// GP0: An AXI (master) port to control the processing logic
	//
	// GP0 32-bit AXI3 wire definitions
	wire		gp0_axi3_AWVALID;
	wire		gp0_axi3_AWREADY;
	wire	[11:0]	gp0_axi3_AWID;
	wire	[31:0]	gp0_axi3_AWADDR;
	wire	[3:0]	gp0_axi3_AWLEN;
	wire	[2:0]	gp0_axi3_AWSIZE;
	wire	[1:0]	gp0_axi3_AWBURST;
	wire	[1:0]	gp0_axi3_AWLOCK;
	wire	[3:0]	gp0_axi3_AWCACHE;
	wire	[2:0]	gp0_axi3_AWPROT;
	wire	[3:0]	gp0_axi3_AWQOS;
		//
	wire		gp0_axi3_WVALID;
	wire		gp0_axi3_WREADY;
	wire	[11:0]	gp0_axi3_WID;
	wire	[31:0]	gp0_axi3_WDATA;
	wire	[3:0]	gp0_axi3_WSTRB;
	wire		gp0_axi3_WLAST;
		//
	wire		gp0_axi3_BVALID;
	wire		gp0_axi3_BREADY;
	wire	[11:0]	gp0_axi3_BID;
	wire	[1:0]	gp0_axi3_BRESP;
		//
	wire		gp0_axi3_ARVALID;
	wire		gp0_axi3_ARREADY;
	wire	[11:0]	gp0_axi3_ARID;
	wire	[31:0]	gp0_axi3_ARADDR;
	wire	[3:0]	gp0_axi3_ARLEN;
	wire	[2:0]	gp0_axi3_ARSIZE;
	wire	[1:0]	gp0_axi3_ARBURST;
	wire	[1:0]	gp0_axi3_ARLOCK;
	wire	[3:0]	gp0_axi3_ARCACHE;
	wire	[2:0]	gp0_axi3_ARPROT;
	wire	[3:0]	gp0_axi3_ARQOS;
		//
	wire		gp0_axi3_RVALID;
	wire		gp0_axi3_RREADY;
	wire	[11:0]	gp0_axi3_RID;
	wire	[31:0]	gp0_axi3_RDATA;
	wire		gp0_axi3_RLAST;
	wire	[1:0]	gp0_axi3_RRESP;
	//
	// GP0 32-bit AXI4 wire definitions
	wire		gp0_axi4_AWVALID;
	wire		gp0_axi4_AWREADY;
	wire	[11:0]	gp0_axi4_AWID;
	wire	[31:0]	gp0_axi4_AWADDR;
	wire	[7:0]	gp0_axi4_AWLEN;
	wire	[2:0]	gp0_axi4_AWSIZE;
	wire	[1:0]	gp0_axi4_AWBURST;
	wire		gp0_axi4_AWLOCK;
	wire	[3:0]	gp0_axi4_AWCACHE;
	wire	[2:0]	gp0_axi4_AWPROT;
	wire	[3:0]	gp0_axi4_AWQOS;
		//
	wire		gp0_axi4_WVALID;
	wire		gp0_axi4_WREADY;
	// [11:0]	gp0_axi4_WID;
	wire	[31:0]	gp0_axi4_WDATA;
	wire	[3:0]	gp0_axi4_WSTRB;
	wire		gp0_axi4_WLAST;
		//
	wire		gp0_axi4_BVALID;
	wire		gp0_axi4_BREADY;
	wire	[11:0]	gp0_axi4_BID;
	wire	 [1:0]	gp0_axi4_BRESP;
		//
	wire		gp0_axi4_ARVALID;
	wire		gp0_axi4_ARREADY;
	wire	[11:0]	gp0_axi4_ARID;
	wire	[31:0]	gp0_axi4_ARADDR;
	wire	[7:0]	gp0_axi4_ARLEN;
	wire	[2:0]	gp0_axi4_ARSIZE;
	wire	[1:0]	gp0_axi4_ARBURST;
	wire		gp0_axi4_ARLOCK;
	wire	[3:0]	gp0_axi4_ARCACHE;
	wire	[2:0]	gp0_axi4_ARPROT;
	wire	[3:0]	gp0_axi4_ARQOS;
		//
	wire		gp0_axi4_RVALID;
	wire		gp0_axi4_RREADY;
	wire [11:0]	gp0_axi4_RID;
	wire [31:0]	gp0_axi4_RDATA;
	wire		gp0_axi4_RLAST;
	wire	[1:0]	gp0_axi4_RRESP;
	//
	// HP0: An AXI (slave) port to write memory from PL
	//
	// HP0 64-bit AXI3 wire definitions
	wire		hp0_axi3_AWVALID;
	wire		hp0_axi3_AWREADY;
	wire	[5:0]	hp0_axi3_AWID;
	wire	[31:0]	hp0_axi3_AWADDR;
	wire	[3:0]	hp0_axi3_AWLEN;
	wire	[2:0]	hp0_axi3_AWSIZE;
	wire	[1:0]	hp0_axi3_AWBURST;
	wire	[1:0]	hp0_axi3_AWLOCK;
	wire	[3:0]	hp0_axi3_AWCACHE;
	wire	[2:0]	hp0_axi3_AWPROT;
	wire	[3:0]	hp0_axi3_AWQOS;
		//
	wire		hp0_axi3_WVALID;
	wire		hp0_axi3_WREADY;
	wire	[5:0]	hp0_axi3_WID;
	wire	[63:0]	hp0_axi3_WDATA;
	wire	[7:0]	hp0_axi3_WSTRB;
	wire		hp0_axi3_WLAST;
		//
	wire		hp0_axi3_BVALID;
	wire		hp0_axi3_BREADY;
	wire	[5:0]	hp0_axi3_BID;
	wire	[1:0]	hp0_axi3_BRESP;
		//
	wire		hp0_axi3_ARVALID;
	wire		hp0_axi3_ARREADY;
	wire	[5:0]	hp0_axi3_ARID;
	wire	[31:0]	hp0_axi3_ARADDR;
	wire	[3:0]	hp0_axi3_ARLEN;
	wire	[2:0]	hp0_axi3_ARSIZE;
	wire	[1:0]	hp0_axi3_ARBURST;
	wire	[1:0]	hp0_axi3_ARLOCK;
	wire	[3:0]	hp0_axi3_ARCACHE;
	wire	[2:0]	hp0_axi3_ARPROT;
	wire	[3:0]	hp0_axi3_ARQOS;
		//
	wire		hp0_axi3_RVALID;
	wire		hp0_axi3_RREADY;
	wire	[5:0]	hp0_axi3_RID;
	wire	[63:0]	hp0_axi3_RDATA;
	wire		hp0_axi3_RLAST;
	wire	[1:0]	hp0_axi3_RRESP;
	//
	// GP0 32-bit AXI4 wire definitions
	wire		hp0_axi4_AWVALID;
	wire		hp0_axi4_AWREADY;
	wire	[5:0]	hp0_axi4_AWID;
	wire	[31:0]	hp0_axi4_AWADDR;
	wire	[7:0]	hp0_axi4_AWLEN;
	wire	[2:0]	hp0_axi4_AWSIZE;
	wire	[1:0]	hp0_axi4_AWBURST;
	wire		hp0_axi4_AWLOCK;
	wire	[3:0]	hp0_axi4_AWCACHE;
	wire	[2:0]	hp0_axi4_AWPROT;
	wire	[3:0]	hp0_axi4_AWQOS;
		//
	wire		hp0_axi4_WVALID;
	wire		hp0_axi4_WREADY;
	// [5:0]	hp0_axi4_WID;
	wire	[63:0]	hp0_axi4_WDATA;
	wire	[7:0]	hp0_axi4_WSTRB;
	wire		hp0_axi4_WLAST;
		//
	wire		hp0_axi4_BVALID;
	wire		hp0_axi4_BREADY;
	wire	[5:0]	hp0_axi4_BID;
	wire	[1:0]	hp0_axi4_BRESP;
		//
	wire		hp0_axi4_ARVALID;
	wire		hp0_axi4_ARREADY;
	wire	[5:0]	hp0_axi4_ARID;
	wire	[31:0]	hp0_axi4_ARADDR;
	wire	[7:0]	hp0_axi4_ARLEN;
	wire	[2:0]	hp0_axi4_ARSIZE;
	wire	[1:0]	hp0_axi4_ARBURST;
	wire		hp0_axi4_ARLOCK;
	wire	[3:0]	hp0_axi4_ARCACHE;
	wire	[2:0]	hp0_axi4_ARPROT;
	wire	[3:0]	hp0_axi4_ARQOS;
		//
	wire		hp0_axi4_RVALID;
	wire		hp0_axi4_RREADY;
	wire	[5:0]	hp0_axi4_RID;
	wire	[63:0]	hp0_axi4_RDATA;
	wire		hp0_axi4_RLAST;
	wire	[1:0]	hp0_axi4_RRESP;
	//
	wire	hp0_wrissuecap1_en, hp0_rdissuecap1_en;
	wire	[5:0]	hp0_wacount;
	wire	[7:0]	hp0_wcount;
	wire	[2:0]	hp0_racount;
	wire	[7:0]	hp0_rcount;
	wire			s_clk, s_reset;
	wire	[53:0]		MIO;
	wire			FCLK_CLK0;
	wire			FCLK_RESET0_N;
	wire			gp0_aclk, gp0_aresetn;
	wire			hp0_aclk, hp0_aresetn;
	reg			r_reset;	
	reg	[2:0]		reset_pipe;


	//
	// Time to call the main module within main.v.  Remember, the purpose
	// of the main.v module is to contain all of our portable logic.
	// Things that are Xilinx (or even Altera) specific, or for that
	// matter anything that requires something other than on-off logic,
	// such as the high impedence states required by many wires, is
	// kept in this (toplevel.v) module.  Everything else goes in
	// main.v.
	//
	// We automatically place s_clk, and s_reset here.  You may need
	// to define those above.  (You did, didn't you?)  Other
	// component descriptions come from the keys @TOP.MAIN (if it
	// exists), or @MAIN.PORTLIST if it does not.
	//

	main	thedesign(s_clk, s_reset,
		gp0_axi4_AWVALID,
		gp0_axi4_AWREADY,
		gp0_axi4_AWID,
		gp0_axi4_AWADDR,
		gp0_axi4_AWLEN,
		gp0_axi4_AWSIZE,
		gp0_axi4_AWBURST,
		gp0_axi4_AWLOCK,
		gp0_axi4_AWCACHE,
		gp0_axi4_AWPROT,
		gp0_axi4_AWQOS,
		//
		gp0_axi4_WVALID,
		gp0_axi4_WREADY,
		// gp0_axi4_WID,
		gp0_axi4_WDATA,
		gp0_axi4_WSTRB,
		gp0_axi4_WLAST,
		//
		gp0_axi4_BVALID,
		gp0_axi4_BREADY,
		gp0_axi4_BID,
		gp0_axi4_BRESP,
		//
		gp0_axi4_ARVALID,
		gp0_axi4_ARREADY,
		gp0_axi4_ARID,
		gp0_axi4_ARADDR,
		gp0_axi4_ARLEN,
		gp0_axi4_ARSIZE,
		gp0_axi4_ARBURST,
		gp0_axi4_ARLOCK,
		gp0_axi4_ARCACHE,
		gp0_axi4_ARPROT,
		gp0_axi4_ARQOS,
		//
		gp0_axi4_RVALID,
		gp0_axi4_RREADY,
		gp0_axi4_RID,
		gp0_axi4_RDATA,
		gp0_axi4_RLAST,
		gp0_axi4_RRESP,
		hp0_axi4_AWVALID,
		hp0_axi4_AWREADY,
		hp0_axi4_AWID,
		hp0_axi4_AWADDR,
		hp0_axi4_AWLEN,
		hp0_axi4_AWSIZE,
		hp0_axi4_AWBURST,
		hp0_axi4_AWLOCK,
		hp0_axi4_AWCACHE,
		hp0_axi4_AWPROT,
		hp0_axi4_AWQOS,
		//
		hp0_axi4_WVALID,
		hp0_axi4_WREADY,
		hp0_axi4_WDATA,
		hp0_axi4_WSTRB,
		hp0_axi4_WLAST,
		//
		hp0_axi4_BVALID,
		hp0_axi4_BREADY,
		hp0_axi4_BID,
		hp0_axi4_BRESP,
		//
		hp0_axi4_ARVALID,
		hp0_axi4_ARREADY,
		hp0_axi4_ARID,
		hp0_axi4_ARADDR,
		hp0_axi4_ARLEN,
		hp0_axi4_ARSIZE,
		hp0_axi4_ARBURST,
		hp0_axi4_ARLOCK,
		hp0_axi4_ARCACHE,
		hp0_axi4_ARPROT,
		hp0_axi4_ARQOS,
		//
		hp0_axi4_RVALID,
		hp0_axi4_RREADY,
		hp0_axi4_RID,
		hp0_axi4_RDATA,
		hp0_axi4_RLAST,
		hp0_axi4_RRESP,
		//
		hp0_wrissuecap1_en, hp0_rdissuecap1_en,
		hp0_wacount,
		hp0_wcount,
		hp0_racount,
		hp0_rcount,
		i_sw, i_btn, o_led,
		o_redled, o_grnled, o_bluled);


	//
	// Our final section to the toplevel is used to provide all of
	// that special logic that couldnt fit in main.  This logic is
	// given by the @TOP.INSERT tag in our data files.
	//


	//
	// Convert the GP0 signals from AXI3 to AXI4
	axi32axi #(
		.C_AXI_ID_WIDTH(12),
		.C_AXI_ADDR_WIDTH(32),
		.C_AXI_DATA_WIDTH(32)
	) gp0_axi3_axi4 (
		.S_AXI_ACLK(gp0_aclk),
		.S_AXI_ARESETN(gp0_aresetn),
		//
		// GP0 32-bit AXI3 connections
		//
		.S_AXI_AWVALID(gp0_axi3_AWVALID && gp0_aresetn),
		.S_AXI_AWREADY(gp0_axi3_AWREADY),
		.S_AXI_AWID(   gp0_axi3_AWID),
		.S_AXI_AWADDR( gp0_axi3_AWADDR),
		.S_AXI_AWLEN(  gp0_axi3_AWLEN),
		.S_AXI_AWSIZE( gp0_axi3_AWSIZE),
		.S_AXI_AWBURST(gp0_axi3_AWBURST),
		.S_AXI_AWLOCK( gp0_axi3_AWLOCK),
		.S_AXI_AWCACHE(gp0_axi3_AWCACHE),
		.S_AXI_AWPROT( gp0_axi3_AWPROT),
		.S_AXI_AWQOS(  gp0_axi3_AWQOS),
		//
		.S_AXI_WVALID(gp0_axi3_WVALID && gp0_aresetn),
		.S_AXI_WREADY(gp0_axi3_WREADY),
		.S_AXI_WID(   gp0_axi3_WID),
		.S_AXI_WDATA( gp0_axi3_WDATA),
		.S_AXI_WSTRB( gp0_axi3_WSTRB),
		.S_AXI_WLAST( gp0_axi3_WLAST),
		//
		.S_AXI_BVALID(gp0_axi3_BVALID),
		.S_AXI_BREADY(gp0_axi3_BREADY && gp0_aresetn),
		.S_AXI_BID(   gp0_axi3_BID),
		.S_AXI_BRESP( gp0_axi3_BRESP),
		//
		.S_AXI_ARVALID(gp0_axi3_ARVALID && gp0_aresetn),
		.S_AXI_ARREADY(gp0_axi3_ARREADY),
		.S_AXI_ARID(   gp0_axi3_ARID),
		.S_AXI_ARADDR( gp0_axi3_ARADDR),
		.S_AXI_ARLEN(  gp0_axi3_ARLEN),
		.S_AXI_ARSIZE( gp0_axi3_ARSIZE),
		.S_AXI_ARBURST(gp0_axi3_ARBURST),
		.S_AXI_ARLOCK( gp0_axi3_ARLOCK),
		.S_AXI_ARCACHE(gp0_axi3_ARCACHE),
		.S_AXI_ARPROT( gp0_axi3_ARPROT),
		.S_AXI_ARQOS(  gp0_axi3_ARQOS),
		//
		.S_AXI_RVALID(gp0_axi3_RVALID),
		.S_AXI_RREADY(gp0_axi3_RREADY && gp0_aresetn),
		.S_AXI_RID(   gp0_axi3_RID),
		.S_AXI_RDATA( gp0_axi3_RDATA),
		.S_AXI_RLAST( gp0_axi3_RLAST),
		.S_AXI_RRESP( gp0_axi3_RRESP),
		//
		// GP0 32-bit AXI4 (outgoing) connections
		//
		.M_AXI_AWVALID(gp0_axi4_AWVALID),
		.M_AXI_AWREADY(gp0_axi4_AWREADY),
		.M_AXI_AWID(   gp0_axi4_AWID),
		.M_AXI_AWADDR( gp0_axi4_AWADDR),
		.M_AXI_AWLEN(  gp0_axi4_AWLEN),
		.M_AXI_AWSIZE( gp0_axi4_AWSIZE),
		.M_AXI_AWBURST(gp0_axi4_AWBURST),
		.M_AXI_AWLOCK( gp0_axi4_AWLOCK),
		.M_AXI_AWCACHE(gp0_axi4_AWCACHE),
		.M_AXI_AWPROT( gp0_axi4_AWPROT),
		.M_AXI_AWQOS(  gp0_axi4_AWQOS),
		//
		.M_AXI_WVALID( gp0_axi4_WVALID),
		.M_AXI_WREADY(gp0_axi4_WREADY),
		// .M_AXI_WID(   gp0_axi4_WID),
		.M_AXI_WDATA( gp0_axi4_WDATA),
		.M_AXI_WSTRB( gp0_axi4_WSTRB),
		.M_AXI_WLAST( gp0_axi4_WLAST),
		//
		.M_AXI_BVALID(gp0_axi4_BVALID),
		.M_AXI_BREADY(gp0_axi4_BREADY),
		.M_AXI_BID(   gp0_axi4_BID),
		.M_AXI_BRESP( gp0_axi4_BRESP),
		//
		.M_AXI_ARVALID(gp0_axi4_ARVALID),
		.M_AXI_ARREADY(gp0_axi4_ARREADY),
		.M_AXI_ARID(   gp0_axi4_ARID),
		.M_AXI_ARADDR( gp0_axi4_ARADDR),
		.M_AXI_ARLEN(  gp0_axi4_ARLEN),
		.M_AXI_ARSIZE( gp0_axi4_ARSIZE),
		.M_AXI_ARBURST(gp0_axi4_ARBURST),
		.M_AXI_ARLOCK( gp0_axi4_ARLOCK),
		.M_AXI_ARCACHE(gp0_axi4_ARCACHE),
		.M_AXI_ARPROT( gp0_axi4_ARPROT),
		.M_AXI_ARQOS(  gp0_axi4_ARQOS),
		//
		.M_AXI_RVALID(gp0_axi4_RVALID),
		.M_AXI_RREADY(gp0_axi4_RREADY),
		.M_AXI_RID(   gp0_axi4_RID),
		.M_AXI_RDATA( gp0_axi4_RDATA),
		.M_AXI_RLAST( gp0_axi4_RLAST),
		.M_AXI_RRESP( gp0_axi4_RRESP)
		);

	//
	// Convert the HP0 signals from AXI4 to AXI3
	axi2axi3 #(
		.C_AXI_ID_WIDTH(7),
		.C_AXI_ADDR_WIDTH(32),
		.C_AXI_DATA_WIDTH(64)
	) hp0_axi4_axi3 (
		.S_AXI_ACLK(hp0_aclk),
		.S_AXI_ARESETN(hp0_aresetn),
		//
		// HP0 AXI4 connections
		//
		.S_AXI_AWVALID(hp0_axi4_AWVALID),
		.S_AXI_AWREADY(hp0_axi4_AWREADY),
		.S_AXI_AWID(   hp0_axi4_AWID),
		.S_AXI_AWADDR( hp0_axi4_AWADDR),
		.S_AXI_AWLEN(  hp0_axi4_AWLEN),
		.S_AXI_AWSIZE( hp0_axi4_AWSIZE),
		.S_AXI_AWBURST(hp0_axi4_AWBURST),
		.S_AXI_AWLOCK( hp0_axi4_AWLOCK),
		.S_AXI_AWCACHE(hp0_axi4_AWCACHE),
		.S_AXI_AWPROT( hp0_axi4_AWPROT),
		.S_AXI_AWQOS(  hp0_axi4_AWQOS),
		//
		.S_AXI_WVALID(hp0_axi4_WVALID),
		.S_AXI_WREADY(hp0_axi4_WREADY),
		// .S_AXI_WID(hp0_axi4_WID),
		.S_AXI_WDATA( hp0_axi4_WDATA),
		.S_AXI_WSTRB( hp0_axi4_WSTRB),
		.S_AXI_WLAST( hp0_axi4_WLAST),
		//
		.S_AXI_BVALID(hp0_axi4_BVALID),
		.S_AXI_BREADY(hp0_axi4_BREADY),
		.S_AXI_BID(   hp0_axi4_BID),
		.S_AXI_BRESP( hp0_axi4_BRESP),
		//
		.S_AXI_ARVALID(hp0_axi4_ARVALID),
		.S_AXI_ARREADY(hp0_axi4_ARREADY),
		.S_AXI_ARID(   hp0_axi4_ARID),
		.S_AXI_ARADDR( hp0_axi4_ARADDR),
		.S_AXI_ARLEN(  hp0_axi4_ARLEN),
		.S_AXI_ARSIZE( hp0_axi4_ARSIZE),
		.S_AXI_ARBURST(hp0_axi4_ARBURST),
		.S_AXI_ARLOCK( hp0_axi4_ARLOCK),
		.S_AXI_ARCACHE(hp0_axi4_ARCACHE),
		.S_AXI_ARPROT( hp0_axi4_ARPROT),
		.S_AXI_ARQOS(  hp0_axi4_ARQOS),
		//
		.S_AXI_RVALID(hp0_axi4_RVALID),
		.S_AXI_RREADY(hp0_axi4_RREADY),
		.S_AXI_RID(   hp0_axi4_RID),
		.S_AXI_RDATA( hp0_axi4_RDATA),
		.S_AXI_RLAST( hp0_axi4_RLAST),
		.S_AXI_RRESP( hp0_axi4_RRESP),
		//
		// GP0 32-bit AXI3 (outgoing) connections
		//
		.M_AXI_AWVALID(hp0_axi3_AWVALID),
		.M_AXI_AWREADY(hp0_axi3_AWREADY),
		.M_AXI_AWID(   hp0_axi3_AWID),
		.M_AXI_AWADDR( hp0_axi3_AWADDR),
		.M_AXI_AWLEN(  hp0_axi3_AWLEN),
		.M_AXI_AWSIZE( hp0_axi3_AWSIZE),
		.M_AXI_AWBURST(hp0_axi3_AWBURST),
		.M_AXI_AWLOCK( hp0_axi3_AWLOCK),
		.M_AXI_AWCACHE(hp0_axi3_AWCACHE),
		.M_AXI_AWPROT( hp0_axi3_AWPROT),
		.M_AXI_AWQOS(  hp0_axi3_AWQOS),
		//
		.M_AXI_WVALID(hp0_axi3_WVALID),
		.M_AXI_WREADY(hp0_axi3_WREADY),
		.M_AXI_WID(   hp0_axi3_WID),
		.M_AXI_WDATA( hp0_axi3_WDATA),
		.M_AXI_WSTRB( hp0_axi3_WSTRB),
		.M_AXI_WLAST( hp0_axi3_WLAST),
		//
		.M_AXI_BVALID(hp0_axi3_BVALID),
		.M_AXI_BREADY(hp0_axi3_BREADY),
		.M_AXI_BID(   hp0_axi3_BID),
		.M_AXI_BRESP( hp0_axi3_BRESP),
		//
		.M_AXI_ARVALID(hp0_axi3_ARVALID),
		.M_AXI_ARREADY(hp0_axi3_ARREADY),
		.M_AXI_ARID(   hp0_axi3_ARID),
		.M_AXI_ARADDR( hp0_axi3_ARADDR),
		.M_AXI_ARLEN(  hp0_axi3_ARLEN),
		.M_AXI_ARSIZE( hp0_axi3_ARSIZE),
		.M_AXI_ARBURST(hp0_axi3_ARBURST),
		.M_AXI_ARLOCK( hp0_axi3_ARLOCK),
		.M_AXI_ARCACHE(hp0_axi3_ARCACHE),
		.M_AXI_ARPROT( hp0_axi3_ARPROT),
		.M_AXI_ARQOS(  hp0_axi3_ARQOS),
		//
		.M_AXI_RVALID(hp0_axi3_RVALID),
		.M_AXI_RREADY(hp0_axi3_RREADY),
		.M_AXI_RID(   hp0_axi3_RID),
		.M_AXI_RDATA( hp0_axi3_RDATA),
		.M_AXI_RLAST( hp0_axi3_RLAST),
		.M_AXI_RRESP( hp0_axi3_RRESP)
		);

	assign	s_clk   = FCLK_CLK0;
	assign	s_reset = r_reset;

	initial { r_reset, reset_pipe } = -1;
	always @(posedge FCLK_CLK0, negedge FCLK_RESET0_N)
	if (!FCLK_RESET0_N)
		{ r_reset, reset_pipe } <= -1;
	else
		{ r_reset, reset_pipe } <= { reset_pipe, 1'b0 };

	assign	gp0_aclk    = FCLK_CLK0;
	assign	gp0_aresetn = !s_reset;
	assign	hp0_aclk    = FCLK_CLK0;
	assign	hp0_aresetn = !s_reset;

	processing_system7_0
	arm_ps(
		.FCLK_CLK0(FCLK_CLK0),
		.FCLK_RESET0_N(FCLK_RESET0_N),
		.MIO(MIO),
		//
		// DDR3 memory connection wires
		.DDR_CAS_n(DDR_CAS_n),
		.DDR_CKE(DDR_CKE),
		.DDR_Clk_n(DDR_Clk_n),
		.DDR_Clk(DDR_Clk),
		.DDR_CS_n(DDR_CS_n),
		.DDR_DRSTB(DDR_DRSTB),
		.DDR_ODT(DDR_ODT),
		.DDR_RAS_n(DDR_RAS_n),
		.DDR_WEB(DDR_WEB),
		.DDR_BankAddr(DDR_BankAddr),
		.DDR_Addr(DDR_Addr),
		.DDR_VRN(DDR_VRN),
		.DDR_VRP(DDR_VRP),
		.DDR_DM(DDR_DM),
		.DDR_DQ(DDR_DQ),
		.DDR_DQS_n(DDR_DQS_n),
		.DDR_DQS(DDR_DQS),
		//
		.PS_SRSTB(PS_SRSTB),
		.PS_CLK(  PS_CLK),
		.PS_PORB( PS_PORB),
		//
				.M_AXI_GP0_ACLK(gp0_aclk),
		// .M_AXI_GP0_ARESETN(gp0_aresetn),
		//
		.M_AXI_GP0_AWVALID(gp0_axi3_AWVALID),
		.M_AXI_GP0_AWREADY(gp0_axi3_AWREADY && gp0_aresetn),
		.M_AXI_GP0_AWID(   gp0_axi3_AWID),
		.M_AXI_GP0_AWADDR( gp0_axi3_AWADDR),
		.M_AXI_GP0_AWLEN(  gp0_axi3_AWLEN),
		.M_AXI_GP0_AWSIZE( gp0_axi3_AWSIZE),
		.M_AXI_GP0_AWBURST(gp0_axi3_AWBURST),
		.M_AXI_GP0_AWLOCK( gp0_axi3_AWLOCK),
		.M_AXI_GP0_AWCACHE(gp0_axi3_AWCACHE),
		.M_AXI_GP0_AWPROT( gp0_axi3_AWPROT),
		.M_AXI_GP0_AWQOS(  gp0_axi3_AWQOS),
		//
		.M_AXI_GP0_WVALID(gp0_axi3_WVALID),
		.M_AXI_GP0_WREADY(gp0_axi3_WREADY && gp0_aresetn),
		.M_AXI_GP0_WID(   gp0_axi3_WID),
		.M_AXI_GP0_WDATA( gp0_axi3_WDATA),
		.M_AXI_GP0_WSTRB( gp0_axi3_WSTRB),
		.M_AXI_GP0_WLAST( gp0_axi3_WLAST),
		//
		.M_AXI_GP0_BVALID(gp0_axi3_BVALID && gp0_aresetn),
		.M_AXI_GP0_BREADY(gp0_axi3_BREADY),
		.M_AXI_GP0_BID(   gp0_axi3_BID),
		.M_AXI_GP0_BRESP( gp0_axi3_BRESP),
		//
		.M_AXI_GP0_ARVALID(gp0_axi3_ARVALID),
		.M_AXI_GP0_ARREADY(gp0_axi3_ARREADY && gp0_aresetn),
		.M_AXI_GP0_ARID(   gp0_axi3_ARID),
		.M_AXI_GP0_ARADDR( gp0_axi3_ARADDR),
		.M_AXI_GP0_ARLEN(  gp0_axi3_ARLEN),
		.M_AXI_GP0_ARSIZE( gp0_axi3_ARSIZE),
		.M_AXI_GP0_ARBURST(gp0_axi3_ARBURST),
		.M_AXI_GP0_ARLOCK( gp0_axi3_ARLOCK),
		.M_AXI_GP0_ARCACHE(gp0_axi3_ARCACHE),
		.M_AXI_GP0_ARPROT( gp0_axi3_ARPROT),
		.M_AXI_GP0_ARQOS(  gp0_axi3_ARQOS),
		//
		.M_AXI_GP0_RVALID(gp0_axi3_RVALID && gp0_aresetn),
		.M_AXI_GP0_RREADY(gp0_axi3_RREADY),
		.M_AXI_GP0_RID(gp0_axi3_RID),
		.M_AXI_GP0_RDATA(gp0_axi3_RDATA),
		.M_AXI_GP0_RLAST(gp0_axi3_RLAST),
		.M_AXI_GP0_RRESP(gp0_axi3_RRESP)
,
				.S_AXI_HP0_ACLK(hp0_aclk),
		//
		.S_AXI_HP0_AWVALID(hp0_axi3_AWVALID && hp0_aresetn),
		.S_AXI_HP0_AWREADY(hp0_axi3_AWREADY),
		.S_AXI_HP0_AWID(   hp0_axi3_AWID),
		.S_AXI_HP0_AWADDR( hp0_axi3_AWADDR),
		.S_AXI_HP0_AWLEN(  hp0_axi3_AWLEN),
		.S_AXI_HP0_AWSIZE( hp0_axi3_AWSIZE),
		.S_AXI_HP0_AWBURST(hp0_axi3_AWBURST),
		.S_AXI_HP0_AWLOCK(hp0_axi3_AWLOCK),
		.S_AXI_HP0_AWCACHE(hp0_axi3_AWCACHE),
		.S_AXI_HP0_AWPROT( hp0_axi3_AWPROT),
		.S_AXI_HP0_AWQOS(  hp0_axi3_AWQOS),
		//
		.S_AXI_HP0_WVALID(hp0_axi3_WVALID && hp0_aresetn),
		.S_AXI_HP0_WREADY(hp0_axi3_WREADY),
		.S_AXI_HP0_WID(   hp0_axi3_WID),
		.S_AXI_HP0_WDATA( hp0_axi3_WDATA),
		.S_AXI_HP0_WSTRB( hp0_axi3_WSTRB),
		.S_AXI_HP0_WLAST( hp0_axi3_WLAST),
		//
		.S_AXI_HP0_BVALID(hp0_axi3_BVALID),
		.S_AXI_HP0_BREADY(hp0_axi3_BREADY || hp0_aresetn),
		.S_AXI_HP0_BID(   hp0_axi3_BID),
		.S_AXI_HP0_BRESP( hp0_axi3_BRESP),
		//
		.S_AXI_HP0_ARVALID(hp0_axi3_ARVALID && hp0_aresetn),
		.S_AXI_HP0_ARREADY(hp0_axi3_ARREADY),
		.S_AXI_HP0_ARID(   hp0_axi3_ARID),
		.S_AXI_HP0_ARADDR( hp0_axi3_ARADDR),
		.S_AXI_HP0_ARLEN(  hp0_axi3_ARLEN),
		.S_AXI_HP0_ARSIZE( hp0_axi3_ARSIZE),
		.S_AXI_HP0_ARBURST(hp0_axi3_ARBURST),
		.S_AXI_HP0_ARLOCK( hp0_axi3_ARLOCK),
		.S_AXI_HP0_ARCACHE(hp0_axi3_ARCACHE),
		.S_AXI_HP0_ARPROT( hp0_axi3_ARPROT),
		.S_AXI_HP0_ARQOS(  hp0_axi3_ARQOS),
		//
		.S_AXI_HP0_RVALID(hp0_axi3_RVALID),
		.S_AXI_HP0_RREADY(hp0_axi3_RREADY || hp0_aresetn),
		.S_AXI_HP0_RID(   hp0_axi3_RID),
		.S_AXI_HP0_RDATA( hp0_axi3_RDATA),
		.S_AXI_HP0_RLAST( hp0_axi3_RLAST),
		.S_AXI_HP0_RRESP( hp0_axi3_RRESP),
		//
		.S_AXI_HP0_WRISSUECAP1_EN(hp0_wrissuecap1_en),
		.S_AXI_HP0_RDISSUECAP1_EN(hp0_rdissuecap1_en),
		.S_AXI_HP0_WACOUNT(hp0_wacount),
		.S_AXI_HP0_WCOUNT( hp0_wcount),
		.S_AXI_HP0_RACOUNT(hp0_racount),
		.S_AXI_HP0_RCOUNT( hp0_rcount)

	);




endmodule // end of toplevel.v module definition
